config/routes.rb
Bookmark::Application.routes.draw do

  resources :links

  resources :categories

     match 'cat_up/:id' => 'categories#move_up'
     match 'link_up/:cat_id/:link_id' => 'links#move_up'
  

   root :to => "pages#home"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :links
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.xml
  def index
    @categories =  Category.find(:all, :order => "position ASC")
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end


  def move_up

    @category = Category.find(params[:id])

    #get all categories and determine index of current
    categories = Category.find(:all,  :order => "position ASC")
    index = categories.index(@category)

   #delete current, and then reinsert one above current (unless current is 0)
    categories.delete_at(index)
    if index != 0
      index = index - 1
    end 
    categories.insert(index, @category)
    
    #reset position of all based on array index
    i = 0
    categories.each do |category|
      category.position = i
      category.save
      i += 1
    end

    redirect_to :action => :index
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # GET /links
  # GET /links.xml
  def index
    @categories = Category.find(:all,  :order => "position ASC")
    #@links = Link.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @links }
    end
  end

  # GET /links/1
  # GET /links/1.xml
  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @link }
    end
  end

  # GET /links/new
  # GET /links/new.xml
  def new
    @link = Link.new

    @categories = Category.find(:all)
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
    @categories = Category.find(:all)
  end

  # POST /links
  # POST /links.xml
  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to(@link, :notice => 'Link was successfully created.') }
        format.xml  { render :xml => @link, :status => :created, :location => @link }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.xml
  def update
    @link = Link.find(params[:id])
    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to(@link, :notice => 'Link was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.xml
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to(links_url) }
      format.xml  { head :ok }
    end
  end


  def move_up

    @link = Link.find(params[:link_id])
    @category = Category.find(params[:cat_id])

    #get all links for chosen category and determine index of current
    links = Link.where("category_id = #{@category.id}").order("position ASC").find(:all)
    index = links.index(@link)

    #delete current, and then reinsert one above current (unless current is 0)
    links.delete_at(index)
    if index != 0
      index = index - 1
    end 
    links.insert(index, @link)

    #reset position of all based on array index
    i = 0
    links.each do |link|
      link.position = i
      link.save
      i += 1
    end

    redirect_to :action => :index
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    categories = Category.find(:all, :order => "position ASC") 
    i = 0
    @left = []
    @right = []

    categories.each do |cat| 
      if i%2 == 0
        @left << cat
      else
        @right << cat
      end
      i += 1
    end
  end

  def add_link

  end

  def destroy_link
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to(links_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Position</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.position %></td>
    <td><a href="cat_up/<%= category.id %>">up</a>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Position:</b>
  <%= @category.position %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookmark</title>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->    
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>
    
    <%= stylesheet_link_tag 'blueprint/plugins/fancy-type/screen.css', :media => 'screen' %>

    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
  </head>
  <body>
   <div class="container">
      <header class="span-21 last">
        <nav class="">
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Category", categories_path %></li>
            <li><%= link_to "Links", links_path %></li>
          </ul>
        </nav>
      </header>
      <section class="round span-21 last">
        
        <%= yield %>
      </section>
        
    </div>

  </body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    
    <%= f.label :category_id %><br />
    <select name="link[<%= :category_id %>]" >
      <% @categories.each do |category| %>
        <option value="<%= category.id %>"><%= category.name %></option>
      <% end %>
    </select>
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<% @categories.each do |category| %>
  <% if category.links.length > 0 %>
    <h2><%= category.name %></h2>
    <table>
      <tr>
        <th>Title</th>
        <th>Url</th>
        <th>Position</th>
        <th>Category</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <% category.links.sort_by{|l| l.position}.each do |link| %>
        <tr>
          <td><%= link.title %></td>
          <td><%= link.url %></td>
          <td><%= link.position %></td>
          <td><%= link.category_id %></td>
          <td><a href="link_up/<%= category.id %>/<%= link.id %>">up</a></td>
          <td><%= link_to 'Show', link %></td>
          <td><%= link_to 'Edit', edit_link_path(link) %></td>
          <td><%= link_to 'Destroy', link, :confirm => 'Are you sure?', :method => :delete %></td>
        </tr>
      <% end %>
    </table>
    <hr/>
  <% end %>
<% end %>

<br />

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @link.title %>
</p>

<p>
  <b>Url:</b>
  <%= @link.url %>
</p>

<p>
  <b>Position:</b>
  <%= @link.position %>
</p>

<p>
  <b>Category:</b>
  <%= @link.category_id %>
</p>


<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/pages/home.html.erb
<div id="logo"  class="span-4">
  <%= image_tag('logo.jpg', :alt => 'logo') %>
</div>

<div id="search"  class="span-16 last">
  <h1 id="title" class="alt" >BookMark</h1>
  <form method="get" action="http://www.google.com/search" target="_blank">
    <input type="text" name="q" size="50" maxlength="255" value="" />
    <input type="submit" value="Google Search" />
  </form>
</div>

<hr />

<div id="left_content" class="span-9 colborder">
  <% @left.each do |category| %>
    <h2  class="alt">
      <%= category.name %>
    </h2>
    <ul>
      <% category.links.sort_by{|c| c.position}.each do |link| %>
        <li><a href="<%= link.url %>" ><%= link.title %></a></li>
      <% end %>
    </ul>
  <% end %>
    </div>

    <div id="right_content" class="span-9 last">
      <% @right.each do |category| %>
        <h2  class="alt">
          <%= category.name %>
        </h2>
        <ul>
          <% category.links.sort_by{|c| c.position}.each do |link| %>
            <li><a href="<%= link.url %>" ><%= link.title %></a></li>
          <% end %>
        </ul>
      <% end %>

  </div>